function [ rotation ] = euler2matrix( angles )

    RX = [1,          0,           0; ...
          0, cos(angles(1)), -sin(angles(1)); ...
          0, sin(angles(1)),  cos(angles(1)) ];

    RY = [cos(angles(2)), 0, -sin(angles(2)); ...
               0,         1,          0; ...
               sin(angles(2)), 0,  cos(angles(2))];

    RZ = [cos(angles(3)), -sin(angles(3)), 0; ...
               sin(angles(3)),  cos(angles(3)), 0; ...
               0,          0,           1];

    rotation = RZ * RY * RX;

end

